### ISSUE TITLE
hidden comment crs are not matching the proj4string source

### ISSUE THREAD

**Issue by mdsumner** [ccamlr/CCAMLRGIS#29]
Sadly something got lost in translation, I see

```
rb <-  load_RBs()

comment(rb@proj4string)
[1] "GEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]"
> 
```

which is just the WKT expansion of "+proj=longlat +datum=WGS84"

but

```
rb@proj4string
CRS arguments:
 +proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m
+no_defs +ellps=WGS84 +towgs84=0,0,0 
```

This means reprojection fails. 

Sadly, the hidden comment *masks* the original and correct coord sys metadata. I would replace rb@proj4string with '+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84`, which is sufficient and correct, and this also sets the comment: 

```
rb@proj4string <- CRS("+proj=laea +lat_0=-90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84")
## it's now set, by the internal machinery
cat(comment(rb@proj4string))
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6326]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8901]]],
    CONVERSION["unknown",
        METHOD["Lambert Azimuthal Equal Area",
            ID["EPSG",9820]],
etc etc
```

Pointed out by @Maschette

I haven't looked at other data sets

**Comment by sthanassekos** [comment]
Hi Mike,

Thanks for pointing that out. We're in the process of changing the way projection arguments will be handled in the package (as well as how the load_ functions will operate). 
The plan is to move to EPSG codes and use 4326 for unprojected data, and, 6932 for laea projections. This is going to take a while, but it seems you'd be able to manually correct the issue for now?

In any case, what do you think about our move to EPSG codes? Your opinion would be very valuable.

Cheers
S.

**Comment by mdsumner** [comment]
👍

**Comment by Maschette** [comment]
EPSG codes are great in one way but they are a pain in the ass in that you have to know what number is the equivalent of each projections. 
If you go down the EPSG route I suggest you put the actual projection string in the R function documentation.

**Comment by sthanassekos** [comment]
Sure why not!

**Comment by Maschette** [comment]
Just as an FYI this issue also effects the SSRU layer.

**Comment by sthanassekos** [comment]
Thanks Dale. It might even affect all layers. We're working on it.
Cheers

**Comment by sthanassekos** [comment]
Hi guys,

Could you please try and update the package? Not sure version 3.0.6 is already available for your platform, but give it a go.
Then please let me know if you're able to re-project.

Cheers
S

**Comment by Sherlock774** [comment]
hi, I'm a new comer for R.  Recently, I want to draw some pictures of the conventions of the CCAMLR. But when I draw the "Basic Map" , the error "unable to find an inherited method for function ‘proj4string’ for signature ‘"character" 'happen all the time.(when I use the projectraster) I can't figure it out. Would you please teach me how to fix the error? Thank you
Your sincerely

**Comment by sthanassekos** [comment]
Hi Sherlock774,

Please read the ReadMe here: https://github.com/ccamlr/CCAMLRGIS

And here is a piece of code (copied from the ReadMe) that could help:

library(CCAMLRGIS)

ASDs=load_ASDs()
EEZs=load_EEZs()
#Set the figure margins as c(bottom, left, top, right)
par(mai=c(0,0.4,0,0))
#Plot the bathymetry
plot(SmallBathy,breaks=Depth_cuts,col=Depth_cols,legend=FALSE,axes=FALSE,box=FALSE)
#Add color scale
add_Cscale(height=65,fontsize=0.4,offset=600,width=25,maxVal=-1,lwd=0.5)
#Add reference grid
add_RefGrid(bb=bbox(SmallBathy),ResLat=10,ResLon=20,LabLon=0,fontsize=0.4,lwd=0.5)
#Add ASD and EEZ boundaries
plot(ASDs,add=TRUE,lwd=0.5,border='red')
plot(EEZs,add=TRUE,lwd=0.5,border='red')
#Add coastline (for all ASDs)
plot(Coast[Coast$ID=='All',],col='grey',lwd=0.01,add=TRUE)
#Add ASD labels
add_labels(mode='auto',layer='ASDs',fontsize=0.3,col='red')

Let me know if you need more assistance.
S.

**Comment by Sherlock774** [comment]
Hi sthanassekos, thanks for your assistance.

 After reading your comments, I find that I forget to install the CCAMLRGIS packages. But though I 'install' and 'library 'the packages. The same error still happen. I suspect that I didn't make it clear the last time. The error message  **"unable to find an inherited method for function ‘proj4string’ for signature ‘"character"** '" just happen in the Section1 'Basemaps' Step5 in Readme. I just copy your code and don't understand why the bug happen. Should I download the latest version of the package?(CCAMLRGIS-3.0.0). It may do some help?

Here are the code:
#Step 1: Download the global GEBCO Grid, from:
#http://www.gebco.net/data_and_products/gridded_bathymetry_data/
#Step 2: load the 'raster' and 'rgeos' libraries
install.packages('CCAMLRGIS')
library(raster)
library(rgeos)
install.packages("ncdf4")
library(ncdf4)
library(CCAMLRGIS)
#Step 3: Read the data
G=raster("D:/CCAMLRGIS-master/gebco_2020_netcdf/GEBCO_2020.nc")
#Step 4: Crop the data to below 40 degrees South
G=crop(G,extent(-180,180,-90,-40))
load("D:/CCAMLRGIS-master/CCAMLR GIS/CCAMLRp.RData")
#Step 5: Project the data using the CCAMLR projection
Gp=projectRaster(G, crs=proj4string(CCAMLRp))
#Step 6: Mask the data using a buffered contour of the Convention area
#load ASDs, buffer them and extract the outer polygon (first polygon within the list of polygons)
ASDs=load_ASDs()
#Build 500km contour
Contour=gBuffer(ASDs,width=500000,quadsegs = 25)
#Extract outer boundary (first polygon)
pol=Contour@polygons[[1]]@Polygons[1]
pol=Polygons(pol,ID='1')
pol=SpatialPolygons(list(pol),proj4string = CRS(CCAMLRp))
#Apply mask
Gpm=mask(Gp, pol)

#Step 7: Clamp the raster to exclude values higher than 500m
Gpmc=clamp(Gpm, upper=500,useValues=F)

#At this point, you may export the data and use it in its native resolution
#Export:
writeRaster(Gpmc,"GEBCOpmc.tif")
#to re-Import:
Gpmc=raster(' Path to the folder containing the GEBCO data /GEBCOpmc.tif')

#Or, resample it (e.g., at a 500m resolution, using the nearest neighbor method):
newR=raster(crs=crs(Gpmc), ext=extent(Gpmc), resolution=500)
Gr=resample(Gpmc,newR,method="ngb")
#Export:
writeRaster(Gr,"GEBCOpmcr500NN.tif")
#to re-Import:
Gpmcr500N=raster(' Path to the folder containing the data /GEBCOpmc.tif')

**Comment by Sherlock774** [comment]
oh sorry! I just find that it's not necessary to draw the BasicMap if I want to draw some local map. But would it be possible to cause some trouble if I don't draw the BasicMap? What's the function of the BasicMap code?
Thank you again.

**Comment by sthanassekos** [comment]
Hi Sherlock774,

The piece of code you copied/pasted in your comment shows the steps to follow if you want to get hi resolution bathymetry. Maybe you don't need that, instead you could use the 'SmallBathy' that is included in the package. As it says in the ReadMe, right before the code you copied:

_Prior to detailing the package’s capabilities, a set of basic commands are shown here to display a few core mapping elements. In a first instance, the code used to produce the bathymetry raster included in the package (‘SmallBathy’) is shown, and may be used to produce a raster at a higher resolution:_

Again, I would encourage you to go through the ReadMe, read it carefully. You might find what you need in there.
