### ISSUE TITLE
load_VMEs()

### ISSUE THREAD

**Issue by charleygros** [ccamlr/CCAMLRGIS#31]
Hi there,

Is there a way to load the VMEs info from the CCAMLR GIS as done with `load_MPAs` for the MPAs, `load_EEZ` for the EEZ etc.?

Cheers,
Charley

**Comment by sthanassekos** [comment]
Hi Charley,

This function might be added in the future. At the moment I would suggest using the VME registry (https://www.ccamlr.org/en/document/data/ccamlr-vme-registry) and the package's create_Points() function. 

Please let me know if you need help.

Cheers
Stephane

**Comment by charleygros** [comment]
Hi Stéphane,
Thanks for your quick reply.

Ok, no worries. I will use `create_Points` for now.

Cheers,
Charley

**Comment by sthanassekos** [comment]
Great, thanks Charley.
Cheers
S.
