### ISSUE TITLE
Missing citation 

### ISSUE THREAD

**Issue by alistairdunn1** [ccamlr/CCAMLRGIS#71]
CCAMLRGIS does not appear to have a citation to be able to reference its use in papers

**Comment by sthanassekos** [comment]
Hi there,

Using the base function citation() works as expected:

citation(package = "CCAMLRGIS")


To cite package ‘CCAMLRGIS’ in publications use:

  Thanassekos S, Reid K, Robinson L (2024).
  _CCAMLRGIS: Antarctic Spatial Data Manipulation_. R
  package version 4.1.1,
  <https://CRAN.R-project.org/package=CCAMLRGIS>.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {CCAMLRGIS: Antarctic Spatial Data Manipulation},
    author = {Stephane Thanassekos and Keith Reid and Lucy Robinson},
    year = {2024},
    note = {R package version 4.1.1},
    url = {https://CRAN.R-project.org/package=CCAMLRGIS},
  }

**Comment by alistairdunn1** [comment]
Thank you!

8/06/2024 21:47:07 Stephane Thanassekos ***@***.***>:
